import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'

import Providers from '@/components/providers'
import { authConfigs } from '@/configs/auth-config'
import { cn } from '@/lib/utils'

import '@/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authConfigs)

  return (
    <html lang='en'>
      <body className={cn(inter.className, 'antialiased transition-all duration-200 ease-in-out')}>
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  )
}
